### ISSUE TITLE
Análisis de requerimientos:

### ISSUE THREAD

**Issue by StivenAtis** [StivenAtis/aplicacion_primaria#1]
1. Profundizar en los requerimientos
2. Presentar propuestas
3. Definir la propuesta que se va a implementar

**Comment by DIANAPANQUEVA** [comment]
![image](https://user-images.githubusercontent.com/90101347/132101651-60d00bc8-c4a6-4ebd-b2c4-d6cbde9026c3.png)

**Comment by dorisgaleano** [comment]
Documento de Análisis de requerimientos iniciales
[requerimientos de software.pdf](https://github.com/StivenAtis/aplicacion_primaria/files/7117907/requerimientos.de.software.pdf)

**Comment by dorisgaleano** [comment]
Reunión por meet del 05/09/2021. 

![image](https://user-images.githubusercontent.com/90101531/132262356-c6df4234-6cbc-48e8-8d1b-97b75e5a0eeb.png)
